---
title: "Meta Analysis"
output:
  html_document:
    code_folding: hide
date: "2024-03-01"
---

```{r setup, include=FALSE} 
knitr::opts_chunk$set(echo= TRUE, warning = FALSE, message = FALSE) 
```

```{r library-instalation}
myPaths <- .libPaths()
myPaths <- c(myPaths, "~/MetaIBS/MetaIBS-library")
myPaths <- c(myPaths[3], myPaths[1], myPaths[2])
.libPaths(myPaths)  # add new path
```

***********
# 1. IMPORT
***********

## 1.1. Libraries

```{r library-import}
library(phyloseq) # Handling and analysis of high-throughput microbiome census data.
library(tidyverse)
library(ggplot2)
library(SpiecEasi)
library(igraph)
library(VennDiagram)
library(NetCoMi)
```

```{r path-directories, echo=FALSE}
# ROOT DIRECTORY (to modify on your computer)
path.root <- "~/MetaIBS"
path.datasets    <- file.path(path.root, "data/Individual/phyloseq_without_tree")
path.phylobj    <- file.path(path.root, "data/Agglomeration/Individual")
path.outputs <- file.path(path.root, "outputs/Individual/single-network-analysis")
path.assoc_mat <- file.path(path.outputs , "association_matrices")
path.plots <- file.path(path.outputs , "plots")

source("~/MetaIBS/scripts/functions.R")
datasets        <- list.files(path.datasets, pattern=".rds")
datasets_names  <- sub(".*_(.*)\\..*", "\\1", datasets)
agg_level <- "Order"
```


******************
# 2. META-ANAYLSIS
******************


```{r function, echo=FALSE}

matrices.gl <- lapply(datasets_names, function(x) {
  load(file=file.path(path.assoc_mat, agg_level, paste0("AssocMat_",x,".RData")))
  objects <- ls()
  return(get(objects[1]))
  })

meta.gl <- meta_analysis(matrices.gl, "mean")
props_asso.gl <- network_construct(meta.gl)

png(file.path(path.plots, agg_level, paste0("Meta-Analysis.png")),
      width=1800, height=1400)
results <- plot(props_asso.gl,
       repulsion = 0.525,
       nodeColor = "cluster",
       labelScale = FALSE,
       rmSingles = TRUE,
       nodeSize = "eigenvector",
       cexNodes = 0.58,
       cexLabels = 1.5,
       cexHubLabels = 1.7,
       title1 = "Meta-Analysis",
       showTitle = TRUE,
       cexTitle = 2,
       hubBorderCol  = "gray40")#,
    # doPlot = F)$layout$layout1

dev.off()

```






