---
title: "Meta analysis - Single Network Analysis (Order)"
output: 
  github_document:
    html_preview: false
date: "2024-03-01"
---

```{r setup, include=FALSE} 
knitr::opts_chunk$set(echo= TRUE, warning = FALSE, message = FALSE, fig.path="../../../outputs/single-network-analysis/plots/Order/") 
```

```{r library-instalation, echo=FALSE}
myPaths <- .libPaths()
myPaths <- c(myPaths, "~/MetaIBS/MetaIBS-library")
myPaths <- c(myPaths[3], myPaths[1], myPaths[2])
.libPaths(myPaths)  # add new path
```

***********
# 1. IMPORT
***********

## 1.1. Libraries

```{r library-import}
library(phyloseq) # Handling and analysis of high-throughput microbiome census data.
library(tidyverse)
library(ggplot2)
library(SpiecEasi)
library(igraph)
library(VennDiagram)
library(NetCoMi)
library(reshape2)
```

```{r path-directories, echo=FALSE}
# ROOT DIRECTORY (to modify on your computer)
path.root <- "~/MetaIBS"
path.datasets    <- file.path(path.root, "data/phyloseq_without_tree")
path.phylobj    <- file.path(path.root, "build/Agglomeration/Individual")
path.outputs <- file.path(path.root, "outputs/single-network-analysis")
path.assoc_mat <- file.path(path.outputs , "association_matrices")
path.properties <- file.path(path.outputs , "network_properties")
path.plots <- file.path(path.outputs , "plots")

source("~/MetaIBS/tools/functions.R")
datasets        <- list.files(path.datasets, pattern=".rds")
datasets_names  <- sub(".*_(.*)\\..*", "\\1", datasets)
agg_level <- "Order"
```

**************
# 2. FUNCTIONS
**************

```{r function, eval=TRUE, echo=FALSE}
# Function to load matrices and filter NULL entries
load_matrices <- function(datasets_names, path.assoc_mat, agg_level, object_index) {
  matrices <- lapply(datasets_names, function(x) {
    tryCatch({
      load(file = file.path(path.assoc_mat, agg_level, paste0("AssocMat_", x, ".RData")))
      objects <- ls()  # Get loaded objects
      return(get(objects[object_index]))  # Return the specified object
    }, error = function(e) {
      message(paste("Skipping file:", x, "due to error:", e$message))
      return(NULL)
    })
  })
  Filter(Negate(is.null), matrices)  # Remove NULL entries
}

# Function to plot meta-analysis
plot_network <- function(meta, layout = NULL, title = "Meta-Analysis", dataType = "condDependence", 
                         thresh = 0, repulsion=0.7, doPlot=T) {
  props_asso_meta <- network_construct(meta, dataType = dataType , thresh = thresh)
  plot(props_asso_meta,
       layout = layout,
       repulsion = repulsion,
       sameLayout = TRUE,
       nodeColor = "cluster",
       labelScale = FALSE,
       rmSingles = TRUE,
       nodeSize = "eigenvector",
       cexNodes = 0.58,
       cexLabels = 0.7,
       cexHubLabels = 1,
       title1 = title,
       showTitle = TRUE,
       cexTitle = 2,
       hubBorderCol = "gray40",
       doPlot=doPlot)
}

# Function to process individual plots
plot_individual_network <- function(matrix, meta, layout,  datasets_names, method) {
  
  sub_adj <- matrix
  
  # Skip if no connected nodes
  if (sum(sub_adj)== 0) {
    message(paste0("Skipping network ", datasets_names[i], " due to no connected nodes."))
    next
  }
  
  common_rows <- intersect(rownames(meta), rownames(sub_adj))
  common_cols <- intersect(colnames(meta), colnames(sub_adj))
  
  filtered_meta_adj <- meta
  filtered_meta_adj[,] <- 0
  
  filtered_meta_adj[common_rows, common_cols] <- meta[common_rows, common_cols] * (sub_adj[common_rows, common_cols] != 0)
  
  props_asso <- network_construct(filtered_meta_adj)
  plot(props_asso,
       layout = layout[common_rows,],
       nodeColor = "cluster",
       labelScale = FALSE,
       rmSingles = "none",#TRUE,
       nodeSize = "eigenvector",
       cexNodes = 0.58,
       cexLabels = 0.7,
       cexHubLabels = 1,
       title1 = paste0("Network Analysis ",  str_to_title(datasets_names)," ",method),
       showTitle = TRUE,
       cexTitle = 1.5,
       hubBorderCol  = "gray40")
  
}

# Function to process individual plots
plot_individual_networks <- function(matrices, meta, layout, datasets_names, method) {
  for (i in seq_along(matrices)) {
    plot_individual_network(matrices[[i]], meta, layout,  datasets_names[[i]], method)
  }
}
```

******************
# 3. META-ANALYSIS
******************

## 3.1. Summary Plots

```{r meta-analysis, out.width="33%", fig.show="hold", fig.align="default", echo=FALSE}

matrices.gl <- load_matrices(datasets_names, path.assoc_mat, agg_level, 1)
matrices.mb <- load_matrices(datasets_names, path.assoc_mat, agg_level, 2)
matrices.slr <- load_matrices(datasets_names, path.assoc_mat, agg_level, 3)

all_matrices <- c(matrices.gl, matrices.mb, matrices.slr)
total_meta <- summary_assoc_matrix(all_matrices, "mean") 

meta_layout <- plot_network(total_meta, title = "", thresh = 0, repulsion = 0.6, doPlot=F)$layout$layout1

meta.gl <- summary_assoc_matrix(matrices.gl, "mean")
meta.mb <- summary_assoc_matrix(matrices.mb, "mean")
meta.slr <- summary_assoc_matrix(matrices.slr, "mean")

prop.gl <- summary_assoc_matrix(matrices.gl, "proportion")
prop.mb <- summary_assoc_matrix(matrices.mb, "proportion")
prop.slr <- summary_assoc_matrix(matrices.slr, "proportion")

result.prop.gl <- plot_network(prop.gl, title = "Proportion Network GLasso",  dataType ="proportionality", thresh = 0)
result.prop.mb <- plot_network(prop.mb, title = "Proportion Network MB",  dataType ="proportionality", thresh = 0)
result.prop.slr <- plot_network(prop.slr, title = "Proportion Network SLR",  dataType ="proportionality", thresh = 0)

### Common associations
asso_g <- network_construct(prop.gl, "proportionality", thresh = 0)$input$assoMat1
asso_mb <- network_construct(prop.mb, "proportionality", thresh = 0)$input$assoMat1
asso_slr <- network_construct(prop.slr, "proportionality", thresh = 0)$input$assoMat1

asso_g <- ifelse(asso_g!=0,1,0)
asso_mb <- ifelse(asso_mb!=0,1,0)
asso_slr <- ifelse(asso_slr!=0,1,0)
common_mat <- asso_g*asso_mb*asso_slr
common_net <- plot_network(common_mat, title = paste0("Common associations - ", agg_level), dataType ="proportionality", thresh = 0)

```

## 3.2. Individual Plots

```{r single-network, out.width="33%", fig.show="hold", fig.align="default", echo=FALSE}

for (i in seq(matrices.gl)){
  mat.gl <- matrices.gl[[i]]
  mat.mb <- matrices.mb[[i]]
  mat.slr <- matrices.slr[[i]]
  
  plot_individual_network(mat.gl, meta.gl, meta_layout, datasets_names[[i]], "GLasso")
  plot_individual_network(mat.mb, meta.mb, meta_layout, datasets_names[[i]], "MB")
  plot_individual_network(mat.slr, meta.slr, meta_layout, datasets_names[[i]], "SLR")
}
```


## 3.3. Global Properties 

### 3.3.1. Summary

```{r global-prop-gl, echo=FALSE}
properties_gl <- process_global_properties(datasets_names, path.properties, agg_level, 1)
properties_mb <- process_global_properties(datasets_names, path.properties, agg_level, 2)
properties_slr <- process_global_properties(datasets_names, path.properties, agg_level, 3)

full_properties <- rbind(properties_gl,properties_mb,properties_slr)
full_properties %>%
  knitr::kable(format = "markdown") 
```

### Some Plots

```{r global-prop-mb, echo=FALSE}
ggplot(full_properties, aes(x = Method, y = Clustering, fill = Method)) +
  geom_boxplot() +
  theme_minimal()

ggplot(full_properties, aes(x = Method, y = Modularity, fill = Method)) +
  geom_boxplot() +
  theme_minimal()

ggplot(full_properties, aes(x = Method, y = Positive_Edges, fill = Method)) +
  geom_boxplot() +
  theme_minimal()

ggplot(full_properties, aes(x = Edge_Density, y = Avg_Path_Length, color = Study, shape = Method)) +
    geom_point(size = 3) +
    geom_smooth(method = "lm", se = FALSE, linetype = "dashed", color = "grey50") +
    theme_minimal() +
    labs(title = "Edge Density vs. Average Path Length",
         x = "Edge Density",
         y = "Average Path Length",
         color = "Method",
         shape = "Study")+facet_wrap(~ Method)
```

### 3.3.3. Hubs

```{r global-prop-slr, fig.width=45, fig.height=15, echo=FALSE}
hub_matrix <- full_properties%>%
  select(Study, Method, Hubs) %>%
  mutate(Hubs = strsplit(Hubs, ",\\s*")) %>%
  unnest(Hubs) %>%
  mutate(Present = 1) %>%
  pivot_wider(names_from = Hubs, values_from = Present, values_fill = 0)

hub_mat <- hub_matrix %>%
  unite("Study_Method", Study, Method, sep = "_") %>%
  column_to_rownames("Study_Method") %>%
  as.matrix()

melted_hub <- melt(hub_mat)
colnames(melted_hub) <- c("Study_Method", "Taxon", "Presence")

melted_hub <- melted_hub %>%
  separate(Study_Method, into = c("Study", "Method"), sep = "_")

ggplot(melted_hub, aes(x = Taxon, y = Study, fill = as.factor(Presence))) +
    geom_tile(color = "grey90") + facet_wrap(~ Method, ncol = 1) +
    scale_fill_manual(values = c("0" = "white", "1" = "steelblue")) +
    theme_minimal()+
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))

melted_hub %>%
    group_by(Taxon) %>%
    summarise(HubCount = sum(Presence)) %>%
    arrange(desc(HubCount))%>%
  knitr::kable(format = "markdown") 

```