---
title: "Meta Analysis - Network Comparison (Genus)"
output: 
  github_document:
    html_preview: false
date: "2024-03-01"
---

```{r setup, include=FALSE} 
knitr::opts_chunk$set(echo= TRUE, warning = FALSE, message = FALSE, fig.path="../../../../outputs/network-comparison/Individual/plots/Genus/")
```

```{r library-instalation}
myPaths <- .libPaths()
myPaths <- c(myPaths, "~/MetaIBS/MetaIBS-library")
myPaths <- c(myPaths[3], myPaths[1], myPaths[2])
.libPaths(myPaths)  # add new path
```

***********
# 1. IMPORT
***********

## 1.1. Libraries

```{r library-import}
library(phyloseq) # Handling and analysis of high-throughput microbiome census data.
library(tidyverse)
library(ggplot2)
library(SpiecEasi)
library(igraph)
library(VennDiagram)
library(NetCoMi)
```

```{r path-directories, echo=FALSE}
# ROOT DIRECTORY (to modify on your computer)
path.root <- "~/MetaIBS"
path.datasets    <- file.path(path.root, "data/Individual/phyloseq_without_tree")
path.phylobj    <- file.path(path.root, "data/Agglomeration/Individual")
path.outputs <- file.path(path.root, "outputs/network-comparison/Individual")
path.assoc_mat <- file.path(path.outputs , "association_matrices")
path.phylobj_sep <- file.path(path.outputs , "phyloseq_IBS")
path.properties <- file.path(path.outputs , "network_properties")
path.plots <- file.path(path.outputs , "plots")

source("~/MetaIBS/scripts/functions.R")
datasets        <- list.files(path.datasets, pattern=".rds")
datasets_names  <- sub(".*_(.*)\\..*", "\\1", datasets)
agg_level <- "Genus"
```

**************
# 2. FUNCTIONS
**************

```{r function, eval=TRUE, echo=FALSE}
# Function to load matrices and filter NULL entries
load_matrices <- function(datasets_names, path.assoc_mat, agg_level, object_index) {
  matrices <- lapply(datasets_names, function(x) {
    tryCatch({
      load(file = file.path(path.assoc_mat, agg_level, paste0("AssocMat_", x, ".RData")))
      objects <- ls()  # Get loaded objects
      return(get(objects[object_index]))  # Return the specified object
    }, error = function(e) {
      message(paste("Skipping file:", x, "due to error:", e$message))
      return(NULL)
    })
  })
  Filter(Negate(is.null), matrices)  # Remove NULL entries
}

# Function to plot meta-analysis comparison
plot_network_comparison <- function(meta_H, meta_IBS, layout = NULL, groupNames = c("Healthy", "IBS"), 
                                    dataType = "condDependence", thresh = 0, repulsion =0.7) {
  props_asso_meta <- network_construct_comparison(meta_H, meta_IBS, dataType = dataType , thresh = thresh)
  plot(props_asso_meta,
       layout = layout,
       repulsion = repulsion,
       sameLayout = TRUE,
       nodeColor = "cluster",
       labelScale = FALSE,
       rmSingles = TRUE,
       nodeSize = "eigenvector",
       cexNodes = 0.58,
       cexLabels = 0.7,
       cexHubLabels = 1,
       #title1 = title,
       groupNames = groupNames,
       showTitle = TRUE,
       cexTitle = 1.5,
       hubBorderCol = "gray40")
}

# Function to process individual plots comparison
plot_individual_network_comparison <- function(matrix_H, matrix_IBS, meta_H, meta_IBS, 
                                                layout, datasets_names, method) {
  sub_adj_H <- matrix_H
  sub_adj_IBS <- matrix_IBS
  
  # Skip if no connected nodes
  if (sum(sub_adj_H) == 0 && sum(sub_adj_IBS) == 0) {
    message(paste0("Skipping network ", datasets_names, " due to no connected nodes."))
    next
  }
  
  common_rows_H <- intersect(rownames(meta_H), rownames(sub_adj_H))
  common_cols_H <- intersect(colnames(meta_H), colnames(sub_adj_H))
  common_rows_IBS <- intersect(rownames(meta_IBS), rownames(sub_adj_IBS))
  common_cols_IBS <- intersect(colnames(meta_IBS), colnames(sub_adj_IBS))
  
  filtered_meta_adj_H <- meta_H
  filtered_meta_adj_IBS <- meta_IBS
  filtered_meta_adj_H[,] <- 0
  filtered_meta_adj_IBS[,] <- 0
  
  filtered_meta_adj_H[common_rows_H, common_cols_H] <- meta_H[common_rows_H, common_cols_H] * (sub_adj_H[common_rows_H, common_cols_H] != 0)
  filtered_meta_adj_IBS[common_rows_IBS, common_cols_IBS] <- meta_IBS[common_rows_IBS, common_cols_IBS] * (sub_adj_IBS[common_rows_IBS, common_cols_IBS] != 0)
  
  props_asso <- network_construct_comparison(filtered_meta_adj_H, filtered_meta_adj_IBS)
  plot(props_asso,
       layout = layout,
       #sameLayout = TRUE,
       nodeColor = "cluster",
       labelScale = FALSE,
       rmSingles = TRUE,
       nodeSize = "eigenvector",
       cexNodes = 0.58,
       cexLabels = 1.5,
       cexHubLabels = 1.7,
       groupNames = c(paste0("Healthy - ", str_to_title(datasets_names)," ",method), 
                      paste0("IBS - ", str_to_title(datasets_names)," ",method)),
       cexTitle = 2,
       hubBorderCol = "gray40")
  
}

plot_individual_networks_comparison <- function(matrices_H, matrices_IBS, meta_H, meta_IBS, 
                                                layout, datasets_names, method) {
  for (i in seq_along(matrices_H)) {
    plot_individual_network_comparison(matrices_H[[i]], matrices_IBS[[i]], meta_H, meta_IBS, 
                                        layout, datasets_names[i], method)
  }
}
```

******************
# 3. META-ANALYSIS
******************

## 3.1. Summary Plots

```{r meta-analysis-glasso, fig.width=30, fig.height=13, echo=FALSE}

matrices_H.gl <- load_matrices(datasets_names, path.assoc_mat, agg_level, 1)
matrices_IBS.gl <- load_matrices(datasets_names, path.assoc_mat, agg_level, 4)
matrices_H.mb <- load_matrices(datasets_names, path.assoc_mat, agg_level, 2)
matrices_IBS.mb <- load_matrices(datasets_names, path.assoc_mat, agg_level, 5)
matrices_H.slr <- load_matrices(datasets_names, path.assoc_mat, agg_level, 3)
matrices_IBS.slr <- load_matrices(datasets_names, path.assoc_mat, agg_level, 6)

meta_H.gl <- summary_assoc_matrix(matrices_H.gl, "mean")
meta_IBS.gl <- summary_assoc_matrix(matrices_IBS.gl, "mean")
meta_H.mb <- summary_assoc_matrix(matrices_H.mb, "mean")
meta_IBS.mb <- summary_assoc_matrix(matrices_IBS.mb, "mean")
meta_H.slr <- summary_assoc_matrix(matrices_H.slr, "mean")
meta_IBS.slr <- summary_assoc_matrix(matrices_IBS.slr, "mean")

thresh_H.gl <- mean(meta_H.gl) + sd(meta_H.gl)
thresh_IBS.gl <- mean(meta_IBS.gl) + sd(meta_IBS.gl)
thresh.gl <- (thresh_H.gl / var(meta_H.gl) + thresh_IBS.gl / var(meta_IBS.gl)) / 
             (1 / var(meta_H.gl) + 1 / var(meta_IBS.gl))
  #mean(thresh_H.gl, thresh_IBS.gl)

thresh_H.mb <- mean(meta_H.mb) + sd(meta_H.mb)
thresh_IBS.mb <- mean(meta_IBS.mb) + sd(meta_IBS.mb)
thresh.mb <- (thresh_H.mb / var(meta_H.mb) + thresh_IBS.mb / var(meta_IBS.mb)) / 
             (1 / var(meta_H.mb) + 1 / var(meta_IBS.mb))

thresh_H.slr <- mean(meta_H.slr) + sd(meta_H.slr)
thresh_IBS.slr <- mean(meta_IBS.slr) + sd(meta_IBS.slr)
thresh.slr <- (thresh_H.slr / var(meta_H.slr) + thresh_IBS.slr / var(meta_IBS.slr)) / 
             (1 / var(meta_H.slr) + 1 / var(meta_IBS.slr))


result.gl <- plot_network_comparison(meta_H.gl, meta_IBS.gl, groupNames = c("Mean Network Healthy GLasso", 
                                                          "Mean Network IBS GLasso"), thresh = thresh.gl,
                                           repulsion = 0.50008)
result.mb <- plot_network_comparison(meta_H.mb, meta_IBS.mb, groupNames = c("Mean Network Healthy MB", 
                                                          "Mean Network IBS MB"), thresh = thresh.mb,
                                           repulsion = 0.50008)
result.slr <- plot_network_comparison(meta_H.slr, meta_IBS.slr, groupNames = c("Mean Network Healthy SLR", 
                                                          "Mean Network IBS SLR"), thresh = thresh.slr,
                                           repulsion = 0.50008)

prop_H.gl <- summary_assoc_matrix(matrices_H.gl, "proportion")
prop_IBS.gl <- summary_assoc_matrix(matrices_IBS.gl, "proportion")
prop_H.mb <- summary_assoc_matrix(matrices_H.mb, "proportion")
prop_IBS.mb <- summary_assoc_matrix(matrices_IBS.mb, "proportion")
prop_H.slr <- summary_assoc_matrix(matrices_H.slr, "proportion")
prop_IBS.slr <- summary_assoc_matrix(matrices_IBS.slr, "proportion")

result.prop.gl <- plot_network_comparison(prop_H.gl, prop_IBS.gl, 
                                          groupNames = c("Proportion Network Healthy GLasso", 
                                                          "Proportion Network IBS GLasso"),  
                               dataType ="proportionality", 
                               thresh = 0.4)
result.prop.gl <- plot_network_comparison(prop_H.mb, prop_IBS.mb, 
                                          groupNames = c("Proportion Network Healthy MB", 
                                                          "Proportion Network IBS MB"),  
                               dataType ="proportionality", 
                               thresh = 0.4)
result.prop.gl <- plot_network_comparison(prop_H.slr, prop_IBS.slr, 
                                          groupNames = c("Proportion Network Healthy SLR", 
                                                          "Proportion Network IBS SLR GLasso"),  
                               dataType ="proportionality", 
                               thresh = 0.4)

### Common associations
net_g <- network_construct_comparison(prop_H.gl, prop_IBS.gl, "proportionality", thresh = 0.4)
asso_H.g <- net_g$input$assoMat1
asso_IBS.g <- net_g$input$assoMat2


net_mb <- network_construct_comparison(prop_H.mb, prop_IBS.mb, "proportionality", thresh = 0.4)
asso_H.mb <- net_mb$input$assoMat1
asso_IBS.mb <- net_mb$input$assoMat2

net_slr <- network_construct_comparison(prop_H.slr, prop_IBS.slr, "proportionality", thresh = 0.4)
asso_H.slr <- net_slr$input$assoMat1
asso_IBS.slr <- net_slr$input$assoMat2

asso_H.g <- ifelse(asso_H.g!=0,1,0)
asso_IBS.g <- ifelse(asso_IBS.g!=0,1,0)
asso_H.mb <- ifelse(asso_H.mb!=0,1,0)
asso_IBS.mb <- ifelse(asso_IBS.mb!=0,1,0)
asso_H.slr <- ifelse(asso_H.slr!=0,1,0)
asso_IBS.slr <- ifelse(asso_IBS.slr!=0,1,0)

common_mat_H <- asso_H.g*asso_H.mb*asso_H.slr
common_mat_IBS <- asso_IBS.g*asso_IBS.mb*asso_IBS.slr

tryCatch({
plot_network_comparison(common_mat_H, common_mat_IBS, 
                                      groupNames = c(paste0("Common associations Healthy - ", agg_level), 
                                                          paste0("Common associations IBS - ", agg_level)),
                                      dataType ="proportionality", thresh = 0)
}, error = function(e) {
  # Custom message when the error occurs
  if (grepl("There are no connected nodes in both networks", e$message)) {
    print("No common associations")
  } else {
    # Re-throw the error if it's a different issue
    stop(e)
  }
})
```

## 3.2. Individual Plots

```{r single-network-glasso, fig.width=30, fig.height=13, echo=FALSE}
layout.gl <- result.gl$layout$layout1
layout.mb <- result.mb$layout$layout1
layout.slr <- result.slr$layout$layout1

for (i in seq(matrices_H.gl)){
  mat_H.gl <- matrices_H.gl[[i]]
  mat_IBS.gl <- matrices_IBS.gl[[i]]
  mat_H.mb <- matrices_H.mb[[i]]
  mat_IBS.mb <- matrices_IBS.mb[[i]]
  mat_H.slr <- matrices_H.slr[[i]]
  mat_IBS.slr <- matrices_IBS.slr[[i]]
  
  plot_individual_network_comparison(mat_H.gl, mat_IBS.gl, meta_H.gl, meta_IBS.gl, 
                                     layout.gl, datasets_names[[i]], "GLasso")
  plot_individual_network_comparison(mat_H.mb, mat_IBS.mb, meta_H.mb, meta_IBS.mb,
                                     layout.mb, datasets_names[[i]], "MB")
  plot_individual_network_comparison(mat_H.slr, mat_IBS.slr, meta_H.slr, meta_H.slr, 
                                     layout.slr, datasets_names[[i]], "SLR")
}
```

## 3.3. Global Properties

### 3.3.1. GLasso

```{r global-prop-gl, echo=FALSE}
merged_df_gl <- process_global_properties_comparison(datasets_names, path.properties, agg_level, 1)
merged_df_gl %>%
  knitr::kable(format = "markdown") 
```

### 3.3.2 MB


```{r global-prop-mb, echo=FALSE}
merged_df_mb <- process_global_properties_comparison(datasets_names, path.properties, agg_level, 2)
merged_df_mb %>%
  knitr::kable(format = "markdown") 
```

### 3.3.3. SLR

```{r global-prop-slr, echo=FALSE}
merged_df_mb <- process_global_properties_comparison(datasets_names, path.properties, agg_level, 3)
merged_df_mb %>%
  knitr::kable(format = "markdown")
```